Update sync.py
Error accessing variable 'gar_wg_state' when only using Withings blood pressure device.  Moved set_lastsyn() under reach fit_data if statements so the other variable isn't used..

UnboundLocalError: cannot access local variable 'gar_wg_state' where it is not associated with a value